### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m1-evaluacion-intermedia-ArianeJDB#1]
Really cool job @ArianeJDB!!!

Here you have some tips to improve the exercise:

//HTML
- [x] Fix the language and the meta title of the page
- [x] Should the `.menu` element be a non-semantics `div` or a rich semantic `nav` (commonly used for our main navigation)
- [x] We need a nav and an h1 tags
- [x] Humanize text in `alt` attributes, a sentence describing the linked image may do the trick.
- [x] Move the font CSS before your main CSS
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, or background-color
- [x] Main section should fit 100% of browser's height
- [x] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)
- [x] There are some weird margins, let's remove them: Remember the browser add some margins to the `<body>` element; and Any time we set an absolute or fixed position on an HTML element we should also set a left/right and a top/bottom CSS properties so it will display properly
- [x] Main title should be vertically and horizontally centered (should we use Flex to achieve this?)
- [x] Finish the main title styles: words should jump and the typography is bolder
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Write your classes in English!
- [x] Try to improve your commit messages, better in English and using imperative
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text
- [ ] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with the main content.

Let me know if you have any doubts ;)

Go for it!!

**Comment by oneeyedman** [comment]
Good job @ArianeJDB!

Some issues need to be fixed:
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto
- [x] We don't need a strong tag inside an h1 one
- [x] The vertical scroll bar appears because of the h1 default margin.
- [x] There is an A tag lost in our HTML code, I think its name is linky.
- [x] Don't forget the header padding ;)

It's almost done. Go for it!

**Comment by ArianeJDB** [comment]
thanks =)!
